# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Trijal/Desktop/integrated_single_boardvfinal.xpr/integrated_single_board/integrated_single_board.cache/wt [current_project]
set_property parent.project_path C:/Users/Trijal/Desktop/integrated_single_boardvfinal.xpr/integrated_single_board/integrated_single_board.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/Trijal/Desktop/integrated_single_boardvfinal.xpr/integrated_single_board/integrated_single_board.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/Trijal/Desktop/integrated_single_boardvfinal.xpr/integrated_single_board/integrated_single_board.srcs/sources_1/new/Font_5X7.v
  C:/Users/Trijal/Desktop/integrated_single_boardvfinal.xpr/integrated_single_board/integrated_single_board.srcs/sources_1/new/Font_5X7_LUT.v
  C:/Users/Trijal/Desktop/integrated_single_boardvfinal.xpr/integrated_single_board/integrated_single_board.srcs/sources_1/new/HP_AND_SKILL.v
  C:/Users/Trijal/Desktop/integrated_single_boardvfinal.xpr/integrated_single_board/integrated_single_board.srcs/sources_1/new/Low_Health_Status_Screen.v
  C:/Users/Trijal/Desktop/integrated_single_boardvfinal.xpr/integrated_single_board/integrated_single_board.srcs/sources_1/new/Oled_Display.v
  C:/Users/Trijal/Desktop/integrated_single_boardvfinal.xpr/integrated_single_board/integrated_single_board.srcs/sources_1/new/bot.v
  C:/Users/Trijal/Desktop/integrated_single_boardvfinal.xpr/integrated_single_board/integrated_single_board.srcs/sources_1/new/bot_buttons.v
  C:/Users/Trijal/Desktop/integrated_single_boardvfinal.xpr/integrated_single_board/integrated_single_board.srcs/sources_1/new/bulbasaur_big.v
  C:/Users/Trijal/Desktop/integrated_single_boardvfinal.xpr/integrated_single_board/integrated_single_board.srcs/sources_1/new/bulbasaur_small.v
  C:/Users/Trijal/Desktop/integrated_single_boardvfinal.xpr/integrated_single_board/integrated_single_board.srcs/sources_1/new/charmander_big_display.v
  C:/Users/Trijal/Desktop/integrated_single_boardvfinal.xpr/integrated_single_board/integrated_single_board.srcs/sources_1/new/charmander_small.v
  C:/Users/Trijal/Desktop/integrated_single_boardvfinal.xpr/integrated_single_board/integrated_single_board.srcs/sources_1/new/confirm_screen.v
  C:/Users/Trijal/Desktop/integrated_single_boardvfinal.xpr/integrated_single_board/integrated_single_board.srcs/sources_1/new/coord.v
  C:/Users/Trijal/Desktop/integrated_single_boardvfinal.xpr/integrated_single_board/integrated_single_board.srcs/sources_1/new/debouncer.v
  C:/Users/Trijal/Desktop/integrated_single_boardvfinal.xpr/integrated_single_board/integrated_single_board.srcs/sources_1/new/display_control.v
  C:/Users/Trijal/Desktop/integrated_single_boardvfinal.xpr/integrated_single_board/integrated_single_board.srcs/sources_1/new/end_screen.v
  C:/Users/Trijal/Desktop/integrated_single_boardvfinal.xpr/integrated_single_board/integrated_single_board.srcs/sources_1/new/five_second_pulse.v
  C:/Users/Trijal/Desktop/integrated_single_boardvfinal.xpr/integrated_single_board/integrated_single_board.srcs/sources_1/new/flex_clk.v
  C:/Users/Trijal/Desktop/integrated_single_boardvfinal.xpr/integrated_single_board/integrated_single_board.srcs/sources_1/new/hp_sp_status.v
  C:/Users/Trijal/Desktop/integrated_single_boardvfinal.xpr/integrated_single_board/integrated_single_board.srcs/sources_1/new/initial_phase.v
  C:/Users/Trijal/Desktop/integrated_single_boardvfinal.xpr/integrated_single_board/integrated_single_board.srcs/sources_1/new/led_control.v
  C:/Users/Trijal/Desktop/integrated_single_boardvfinal.xpr/integrated_single_board/integrated_single_board.srcs/sources_1/new/my_HP_SP_Status_Screen.v
  C:/Users/Trijal/Desktop/integrated_single_boardvfinal.xpr/integrated_single_board/integrated_single_board.srcs/sources_1/new/picopixel.v
  C:/Users/Trijal/Desktop/integrated_single_boardvfinal.xpr/integrated_single_board/integrated_single_board.srcs/sources_1/new/picopixel_LUT.v
  C:/Users/Trijal/Desktop/integrated_single_boardvfinal.xpr/integrated_single_board/integrated_single_board.srcs/sources_1/new/player1.v
  C:/Users/Trijal/Desktop/integrated_single_boardvfinal.xpr/integrated_single_board/integrated_single_board.srcs/sources_1/new/player2.v
  C:/Users/Trijal/Desktop/integrated_single_boardvfinal.xpr/integrated_single_board/integrated_single_board.srcs/sources_1/new/player_interface.v
  C:/Users/Trijal/Desktop/integrated_single_boardvfinal.xpr/integrated_single_board/integrated_single_board.srcs/sources_1/new/player_screen.v
  {C:/Users/Trijal/Desktop/integrated_single_boardvfinal.xpr/integrated_single_board/integrated_single_board.srcs/sources_1/new/poke ani.v}
  C:/Users/Trijal/Desktop/integrated_single_boardvfinal.xpr/integrated_single_board/integrated_single_board.srcs/sources_1/new/rectangle_generator.v
  C:/Users/Trijal/Desktop/integrated_single_boardvfinal.xpr/integrated_single_board/integrated_single_board.srcs/sources_1/new/seven_seg.v
  C:/Users/Trijal/Desktop/integrated_single_boardvfinal.xpr/integrated_single_board/integrated_single_board.srcs/sources_1/new/skillB_cooldown_screen.v
  C:/Users/Trijal/Desktop/integrated_single_boardvfinal.xpr/integrated_single_board/integrated_single_board.srcs/sources_1/new/splash_screen.v
  C:/Users/Trijal/Desktop/integrated_single_boardvfinal.xpr/integrated_single_board/integrated_single_board.srcs/sources_1/new/splash_screen_player1.v
  C:/Users/Trijal/Desktop/integrated_single_boardvfinal.xpr/integrated_single_board/integrated_single_board.srcs/sources_1/new/squirtle_big.v
  C:/Users/Trijal/Desktop/integrated_single_boardvfinal.xpr/integrated_single_board/integrated_single_board.srcs/sources_1/new/squirtle_small.v
  C:/Users/Trijal/Desktop/integrated_single_boardvfinal.xpr/integrated_single_board/integrated_single_board.srcs/sources_1/new/start_screen.v
  C:/Users/Trijal/Desktop/integrated_single_boardvfinal.xpr/integrated_single_board/integrated_single_board.srcs/sources_1/new/waynes_work.v
  C:/Users/Trijal/Desktop/integrated_single_boardvfinal.xpr/integrated_single_board/integrated_single_board.srcs/sources_1/new/main.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Trijal/Desktop/integrated_single_boardvfinal.xpr/integrated_single_board/integrated_single_board.srcs/constrs_1/new/cons.xdc
set_property used_in_implementation false [get_files C:/Users/Trijal/Desktop/integrated_single_boardvfinal.xpr/integrated_single_board/integrated_single_board.srcs/constrs_1/new/cons.xdc]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top main -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef main.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file main_utilization_synth.rpt -pb main_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
